"""empty message

Revision ID: 0417e99338cd
Revises: 
Create Date: 2023-09-23 16:02:20.680993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0417e99338cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_houses', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_houses', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
