"""empty message

Revision ID: b5b626d4f023
Revises: db44db7ba10e
Create Date: 2024-04-16 22:12:24.935188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b626d4f023'
down_revision = 'db44db7ba10e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_houses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kitchen', sa.Boolean(), nullable=True),
    sa.Column('furnished', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_houses_country'), 'tbl_houses', ['country'], unique=False)
    op.create_index(op.f('ix_tbl_houses_district'), 'tbl_houses', ['district'], unique=False)
    op.create_index(op.f('ix_tbl_houses_furnished'), 'tbl_houses', ['furnished'], unique=False)
    op.create_index(op.f('ix_tbl_houses_kitchen'), 'tbl_houses', ['kitchen'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_houses_kitchen'), table_name='tbl_houses')
    op.drop_index(op.f('ix_tbl_houses_furnished'), table_name='tbl_houses')
    op.drop_index(op.f('ix_tbl_houses_district'), table_name='tbl_houses')
    op.drop_index(op.f('ix_tbl_houses_country'), table_name='tbl_houses')
    op.drop_table('tbl_houses')
    # ### end Alembic commands ###
