DISTRITOS_PORTUGAL = [
    "aveiro",
    "beja",
    "braga",
    "braganca",
    "castelo-branco",
    "coimbra",
    "evora",
    "faro",
    "guarda",
    "leiria",
    # "lisboa",
    "portalegre",
    # "porto",
    "santarem",
    "setubal",
    "viana-do-castelo",
    "vila-real",
    "viseu"
]

PROVINCIAS_ESPANHA = [
    "albacete-provincia",
    "almeria-provincia",
    "avila-provincia",
    "badajoz-provincia",
    "barcelona-provincia",
    "burgos-provincia",
    "caceres-provincia",
    "cadiz-provincia",
    "ceuta-provincia",
    "ciudad-real-provincia",
    "cordoba-provincia",
    "a-coruna-provincia",
    "cuenca-provincia",
    "girona-provincia",
    "granada-provincia",
    "guadalajara-provincia",
    "huelva-provincia",
    "huesca-provincia",
    "jaen-provincia",
    "leon-provincia",
    "lleida-provincia",
    "lugo-provincia",
    "madrid-provincia",
    "malaga-provincia",
    "murcia-provincia",
    "ourense-provincia",
    "palencia-provincia",
    "pontevedra-provincia",
    "salamanca-provincia",
    "segovia-provincia",
    "sevilla-provincia",
    "soria-provincia",
    "tarragona-provincia",
    "santa-cruz-de-tenerife-provincia",
    "teruel-provincia",
    "toledo-provincia",
    "valencia-provincia",
    "valladolid-provincia",
    "zamora-provincia",
    "zaragoza-provincia",
    # Without province
    "navarra",
    "las-palmas",
    "la-rioja",
    "alava",
    "alicante",
    "asturias",
    "balears-illes",
    "vizcaya",  # bizkaia
    "cantabria",
    "castellon",
    "guipuzcoa",

]

PROVINCIAS_ESPANHA = ["avila-provincia"]